<x-layouts.app>
    <div class="min-h-screen bg-black py-12 px-4">
        <div class="container mx-auto max-w-4xl">
            <!-- Header -->
            <div class="text-center mb-12">
                <h1 class="text-5xl font-bold text-white mb-3">Metronome</h1>
                <p class="text-gray-400 text-lg">Alat bantu tempo untuk latihan musik</p>
            </div>

            <!-- Main Metronome Card -->
            <div class="bg-white shadow-2xl rounded-2xl p-8 mb-8 border-2 border-black">
                
                <!-- BPM Display -->
                <div class="text-center mb-8">
                    <div class="inline-block">
                        <div class="text-gray-400 text-sm mb-2 uppercase tracking-wider">Tempo</div>
                        <div class="flex items-baseline justify-center gap-2">
                            <input type="number" id="bpmInput" value="120" min="40" max="240"
                                   class="bg-black border-2 border-white text-white text-7xl font-bold text-center w-48 py-4 rounded-lg focus:outline-none focus:ring-4 focus:ring-white">
                            <span class="text-3xl text-gray-400 font-bold">BPM</span>
                        </div>
                        <div id="tempoName" class="text-gray-400 text-sm mt-2 uppercase tracking-wider">Moderato</div>
                    </div>
                </div>

                <!-- BPM Slider -->
                <div class="mb-8">
                    <input type="range" id="bpmSlider" min="40" max="240" value="120"
                           class="w-full h-3 bg-gray-700 rounded-lg appearance-none cursor-pointer slider">
                    <div class="flex justify-between text-xs text-gray-500 mt-2">
                        <span>40</span>
                        <span>140</span>
                        <span>240</span>
                    </div>
                </div>

                <!-- Visual Beat Indicator -->
                <div class="mb-8">
                    <div id="beatIndicator" class="flex justify-center gap-3">
                        <!-- Beats will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Time Signature -->
                <div class="mb-8">
                    <label class="block text-gray-300 text-sm font-bold mb-3 text-center">Time Signature</label>
                    <div class="flex justify-center gap-2">
                        <button onclick="setTimeSignature(2, 4)" class="time-sig-btn px-6 py-3 bg-gray-700 hover:bg-white hover:text-black text-white font-bold rounded-lg transition">2/4</button>
                        <button onclick="setTimeSignature(3, 4)" class="time-sig-btn px-6 py-3 bg-gray-700 hover:bg-white hover:text-black text-white font-bold rounded-lg transition">3/4</button>
                        <button onclick="setTimeSignature(4, 4)" class="time-sig-btn active px-6 py-3 bg-white text-black font-bold rounded-lg transition">4/4</button>
                        <button onclick="setTimeSignature(5, 4)" class="time-sig-btn px-6 py-3 bg-gray-700 hover:bg-white hover:text-black text-white font-bold rounded-lg transition">5/4</button>
                        <button onclick="setTimeSignature(6, 8)" class="time-sig-btn px-6 py-3 bg-gray-700 hover:bg-white hover:text-black text-white font-bold rounded-lg transition">6/8</button>
                    </div>
                </div>

                <!-- Control Buttons -->
                <div class="flex justify-center gap-4 mb-8">
                    <button id="playBtn" onclick="toggleMetronome()" class="bg-white hover:bg-gray-200 text-black font-bold py-4 px-12 rounded-lg transition transform hover:scale-105 text-lg flex items-center gap-2">
                        <svg id="playIcon" class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
                            <path d="M6.3 2.841A1.5 1.5 0 004 4.11V15.89a1.5 1.5 0 002.3 1.269l9.344-5.89a1.5 1.5 0 000-2.538L6.3 2.84z"/>
                        </svg>
                        <span id="playText">Mulai</span>
                    </button>
                    <button onclick="tapTempo()" class="bg-gray-700 hover:bg-gray-600 text-white font-bold py-4 px-8 rounded-lg transition transform hover:scale-105 border-2 border-white">
                        Tap Tempo
                    </button>
                </div>

                <!-- Volume Control -->
                <div class="mb-6">
                    <label class="block text-gray-300 text-sm font-bold mb-3 text-center flex items-center justify-center gap-2">
                        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                            <path fill-rule="evenodd" d="M9.383 3.076A1 1 0 0110 4v12a1 1 0 01-1.707.707L4.586 13H2a1 1 0 01-1-1V8a1 1 0 011-1h2.586l3.707-3.707a1 1 0 011.09-.217zM14.657 2.929a1 1 0 011.414 0A9.972 9.972 0 0119 10a9.972 9.972 0 01-2.929 7.071 1 1 0 01-1.414-1.414A7.971 7.971 0 0017 10c0-2.21-.894-4.208-2.343-5.657a1 1 0 010-1.414zm-2.829 2.828a1 1 0 011.415 0A5.983 5.983 0 0115 10a5.984 5.984 0 01-1.757 4.243 1 1 0 01-1.415-1.415A3.984 3.984 0 0013 10a3.983 3.983 0 00-1.172-2.828 1 1 0 010-1.415z" clip-rule="evenodd"/>
                        </svg>
                        Volume
                    </label>
                    <input type="range" id="volumeSlider" min="0" max="100" value="70"
                           class="w-full h-3 bg-gray-700 rounded-lg appearance-none cursor-pointer slider">
                </div>

                <!-- Accent First Beat Toggle -->
                <div class="flex justify-center">
                    <label class="flex items-center gap-3 cursor-pointer">
                        <input type="checkbox" id="accentToggle" checked class="w-5 h-5 rounded border-2 border-gray-600 bg-gray-700 checked:bg-white checked:border-white">
                        <span class="text-gray-300 font-medium">Accent pada ketukan pertama</span>
                    </label>
                </div>
            </div>

            <!-- Tempo Presets -->
            <div class="bg-white shadow-2xl rounded-2xl p-8 border-2 border-black">
                <h3 class="text-2xl font-bold text-white mb-6 text-center">Preset Tempo</h3>
                <div class="grid grid-cols-2 md:grid-cols-5 gap-4">
                    <button onclick="setBPM(40)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Grave</div>
                        <div class="text-sm opacity-75">40 BPM</div>
                    </button>
                    <button onclick="setBPM(60)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Largo</div>
                        <div class="text-sm opacity-75">60 BPM</div>
                    </button>
                    <button onclick="setBPM(90)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Andante</div>
                        <div class="text-sm opacity-75">90 BPM</div>
                    </button>
                    <button onclick="setBPM(120)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Moderato</div>
                        <div class="text-sm opacity-75">120 BPM</div>
                    </button>
                    <button onclick="setBPM(140)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Allegro</div>
                        <div class="text-sm opacity-75">140 BPM</div>
                    </button>
                    <button onclick="setBPM(168)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Vivace</div>
                        <div class="text-sm opacity-75">168 BPM</div>
                    </button>
                    <button onclick="setBPM(180)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Presto</div>
                        <div class="text-sm opacity-75">180 BPM</div>
                    </button>
                    <button onclick="setBPM(200)" class="preset-btn bg-gray-700 hover:bg-white hover:text-black text-white p-4 rounded-lg transition">
                        <div class="font-bold text-lg">Prestissimo</div>
                        <div class="text-sm opacity-75">200 BPM</div>
                    </button>
                </div>
            </div>
        </div>
    </div>

    <script>
        // Metronome State
        let isPlaying = false;
        let bpm = 120;
        let beatsPerMeasure = 4;
        let currentBeat = 0;
        let intervalId = null;
        let audioContext = null;
        let volume = 0.7;
        let accentFirstBeat = true;

        // Tap Tempo
        let tapTimes = [];
        const maxTapInterval = 2000; // 2 seconds

        // Initialize Audio Context
        function initAudio() {
            if (!audioContext) {
                audioContext = new (window.AudioContext || window.webkitAudioContext)();
            }
        }

        // Play Click Sound
        function playClick(isAccent = false) {
            initAudio();
            
            const oscillator = audioContext.createOscillator();
            const gainNode = audioContext.createGain();
            
            oscillator.connect(gainNode);
            gainNode.connect(audioContext.destination);
            
            // Higher pitch for accent, lower for regular beat
            oscillator.frequency.value = isAccent ? 1200 : 800;
            oscillator.type = 'sine';
            
            // Volume
            gainNode.gain.value = volume * (isAccent ? 1.2 : 0.8);
            
            const now = audioContext.currentTime;
            oscillator.start(now);
            
            // Quick fade out
            gainNode.gain.exponentialRampToValueAtTime(0.01, now + 0.05);
            oscillator.stop(now + 0.05);
        }

        // Update BPM
        function updateBPM(newBPM) {
            bpm = Math.max(40, Math.min(240, parseInt(newBPM)));
            document.getElementById('bpmInput').value = bpm;
            document.getElementById('bpmSlider').value = bpm;
            updateTempoName();
            
            if (isPlaying) {
                stopMetronome();
                startMetronome();
            }
        }

        // Set BPM from preset
        function setBPM(newBPM) {
            updateBPM(newBPM);
        }

        // Update Tempo Name
        function updateTempoName() {
            let name = '';
            if (bpm < 50) name = 'Grave';
            else if (bpm < 70) name = 'Largo';
            else if (bpm < 100) name = 'Andante';
            else if (bpm < 130) name = 'Moderato';
            else if (bpm < 160) name = 'Allegro';
            else if (bpm < 180) name = 'Vivace';
            else if (bpm < 200) name = 'Presto';
            else name = 'Prestissimo';
            
            document.getElementById('tempoName').textContent = name;
        }

        // Set Time Signature
        function setTimeSignature(beats, noteValue) {
            beatsPerMeasure = beats;
            currentBeat = 0;
            
            // Update active button
            document.querySelectorAll('.time-sig-btn').forEach(btn => {
                btn.classList.remove('active', 'bg-white', 'text-black');
                btn.classList.add('bg-gray-700', 'text-white');
            });
            event.target.classList.add('active', 'bg-white', 'text-black');
            event.target.classList.remove('bg-gray-700', 'text-white');
            
            updateBeatIndicator();
        }

        // Update Beat Indicator
        function updateBeatIndicator() {
            const indicator = document.getElementById('beatIndicator');
            indicator.innerHTML = '';
            
            for (let i = 0; i < beatsPerMeasure; i++) {
                const beat = document.createElement('div');
                beat.className = 'beat-dot w-12 h-12 rounded-full border-4 border-white transition-all duration-100';
                beat.id = `beat-${i}`;
                indicator.appendChild(beat);
            }
        }

        // Highlight Current Beat
        function highlightBeat() {
            document.querySelectorAll('.beat-dot').forEach((dot, index) => {
                if (index === currentBeat) {
                    dot.classList.add('bg-white', 'scale-125');
                } else {
                    dot.classList.remove('bg-white', 'scale-125');
                }
            });
        }

        // Start Metronome
        function startMetronome() {
            initAudio();
            isPlaying = true;
            currentBeat = 0;
            
            const interval = (60 / bpm) * 1000;
            
            // Play first beat immediately
            const isAccent = accentFirstBeat && currentBeat === 0;
            playClick(isAccent);
            highlightBeat();
            currentBeat = (currentBeat + 1) % beatsPerMeasure;
            
            intervalId = setInterval(() => {
                const isAccent = accentFirstBeat && currentBeat === 0;
                playClick(isAccent);
                highlightBeat();
                currentBeat = (currentBeat + 1) % beatsPerMeasure;
            }, interval);
            
            updatePlayButton();
        }

        // Stop Metronome
        function stopMetronome() {
            isPlaying = false;
            if (intervalId) {
                clearInterval(intervalId);
                intervalId = null;
            }
            currentBeat = 0;
            
            // Reset beat indicators
            document.querySelectorAll('.beat-dot').forEach(dot => {
                dot.classList.remove('bg-white', 'scale-125');
            });
            
            updatePlayButton();
        }

        // Toggle Metronome
        function toggleMetronome() {
            if (isPlaying) {
                stopMetronome();
            } else {
                startMetronome();
            }
        }

        // Update Play Button
        function updatePlayButton() {
            const playIcon = document.getElementById('playIcon');
            const playText = document.getElementById('playText');
            
            if (isPlaying) {
                playIcon.innerHTML = '<path d="M5 3a2 2 0 00-2 2v10a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM13 3a2 2 0 00-2 2v10a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2h-2z"/>';
                playText.textContent = 'Berhenti';
            } else {
                playIcon.innerHTML = '<path d="M6.3 2.841A1.5 1.5 0 004 4.11V15.89a1.5 1.5 0 002.3 1.269l9.344-5.89a1.5 1.5 0 000-2.538L6.3 2.84z"/>';
                playText.textContent = 'Mulai';
            }
        }

        // Tap Tempo
        function tapTempo() {
            const now = Date.now();
            
            // Remove old taps
            tapTimes = tapTimes.filter(time => now - time < maxTapInterval);
            
            tapTimes.push(now);
            
            if (tapTimes.length >= 2) {
                // Calculate average interval
                let totalInterval = 0;
                for (let i = 1; i < tapTimes.length; i++) {
                    totalInterval += tapTimes[i] - tapTimes[i - 1];
                }
                const avgInterval = totalInterval / (tapTimes.length - 1);
                const newBPM = Math.round(60000 / avgInterval);
                updateBPM(newBPM);
            }
            
            // Visual feedback
            const btn = event.target;
            btn.classList.add('scale-95');
            setTimeout(() => btn.classList.remove('scale-95'), 100);
        }

        // Event Listeners
        document.getElementById('bpmInput').addEventListener('input', (e) => {
            updateBPM(e.target.value);
        });

        document.getElementById('bpmSlider').addEventListener('input', (e) => {
            updateBPM(e.target.value);
        });

        document.getElementById('volumeSlider').addEventListener('input', (e) => {
            volume = e.target.value / 100;
        });

        document.getElementById('accentToggle').addEventListener('change', (e) => {
            accentFirstBeat = e.target.checked;
        });

        // Keyboard shortcuts
        document.addEventListener('keydown', (e) => {
            if (e.code === 'Space') {
                e.preventDefault();
                toggleMetronome();
            } else if (e.code === 'ArrowUp') {
                e.preventDefault();
                updateBPM(bpm + 1);
            } else if (e.code === 'ArrowDown') {
                e.preventDefault();
                updateBPM(bpm - 1);
            } else if (e.code === 'KeyT') {
                e.preventDefault();
                tapTempo();
            }
        });

        // Initialize
        updateTempoName();
        updateBeatIndicator();
    </script>

    <style>
        /* Custom Slider Styles */
        .slider::-webkit-slider-thumb {
            appearance: none;
            width: 24px;
            height: 24px;
            background: white;
            border: 3px solid black;
            border-radius: 50%;
            cursor: pointer;
            transition: all 0.2s;
        }

        .slider::-webkit-slider-thumb:hover {
            transform: scale(1.2);
        }

        .slider::-moz-range-thumb {
            width: 24px;
            height: 24px;
            background: white;
            border: 3px solid black;
            border-radius: 50%;
            cursor: pointer;
            transition: all 0.2s;
        }

        .slider::-moz-range-thumb:hover {
            transform: scale(1.2);
        }

        /* Remove spinner from number input */
        input[type="number"]::-webkit-inner-spin-button,
        input[type="number"]::-webkit-outer-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type="number"] {
            -moz-appearance: textfield;
        }
    </style>
</x-layouts.app>
